// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcHead.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rpcHead_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rpcHead_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rpcHead_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rpcHead_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rpcHead_2eproto;
namespace RPC {
class rpcHead;
class rpcHeadDefaultTypeInternal;
extern rpcHeadDefaultTypeInternal _rpcHead_default_instance_;
}  // namespace RPC
PROTOBUF_NAMESPACE_OPEN
template<> ::RPC::rpcHead* Arena::CreateMaybeMessage<::RPC::rpcHead>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace RPC {

// ===================================================================

class rpcHead PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RPC.rpcHead) */ {
 public:
  inline rpcHead() : rpcHead(nullptr) {};
  virtual ~rpcHead();

  rpcHead(const rpcHead& from);
  rpcHead(rpcHead&& from) noexcept
    : rpcHead() {
    *this = ::std::move(from);
  }

  inline rpcHead& operator=(const rpcHead& from) {
    CopyFrom(from);
    return *this;
  }
  inline rpcHead& operator=(rpcHead&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const rpcHead& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const rpcHead* internal_default_instance() {
    return reinterpret_cast<const rpcHead*>(
               &_rpcHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(rpcHead& a, rpcHead& b) {
    a.Swap(&b);
  }
  inline void Swap(rpcHead* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(rpcHead* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline rpcHead* New() const final {
    return CreateMaybeMessage<rpcHead>(nullptr);
  }

  rpcHead* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<rpcHead>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const rpcHead& from);
  void MergeFrom(const rpcHead& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(rpcHead* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RPC.rpcHead";
  }
  protected:
  explicit rpcHead(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rpcHead_2eproto);
    return ::descriptor_table_rpcHead_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceNameFieldNumber = 1,
    kMethodNameFieldNumber = 2,
    kArgsSizeFieldNumber = 3,
  };
  // bytes service_name_ = 1;
  void clear_service_name_();
  const std::string& service_name_() const;
  void set_service_name_(const std::string& value);
  void set_service_name_(std::string&& value);
  void set_service_name_(const char* value);
  void set_service_name_(const void* value, size_t size);
  std::string* mutable_service_name_();
  std::string* release_service_name_();
  void set_allocated_service_name_(std::string* service_name_);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_service_name_();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_service_name_(
      std::string* service_name_);
  private:
  const std::string& _internal_service_name_() const;
  void _internal_set_service_name_(const std::string& value);
  std::string* _internal_mutable_service_name_();
  public:

  // bytes method_name_ = 2;
  void clear_method_name_();
  const std::string& method_name_() const;
  void set_method_name_(const std::string& value);
  void set_method_name_(std::string&& value);
  void set_method_name_(const char* value);
  void set_method_name_(const void* value, size_t size);
  std::string* mutable_method_name_();
  std::string* release_method_name_();
  void set_allocated_method_name_(std::string* method_name_);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_method_name_();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_method_name_(
      std::string* method_name_);
  private:
  const std::string& _internal_method_name_() const;
  void _internal_set_method_name_(const std::string& value);
  std::string* _internal_mutable_method_name_();
  public:

  // int32 args_size_ = 3;
  void clear_args_size_();
  ::PROTOBUF_NAMESPACE_ID::int32 args_size_() const;
  void set_args_size_(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_args_size_() const;
  void _internal_set_args_size_(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:RPC.rpcHead)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_name__;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_name__;
  ::PROTOBUF_NAMESPACE_ID::int32 args_size__;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rpcHead_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// rpcHead

// bytes service_name_ = 1;
inline void rpcHead::clear_service_name_() {
  service_name__.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& rpcHead::service_name_() const {
  // @@protoc_insertion_point(field_get:RPC.rpcHead.service_name_)
  return _internal_service_name_();
}
inline void rpcHead::set_service_name_(const std::string& value) {
  _internal_set_service_name_(value);
  // @@protoc_insertion_point(field_set:RPC.rpcHead.service_name_)
}
inline std::string* rpcHead::mutable_service_name_() {
  // @@protoc_insertion_point(field_mutable:RPC.rpcHead.service_name_)
  return _internal_mutable_service_name_();
}
inline const std::string& rpcHead::_internal_service_name_() const {
  return service_name__.Get();
}
inline void rpcHead::_internal_set_service_name_(const std::string& value) {
  
  service_name__.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void rpcHead::set_service_name_(std::string&& value) {
  
  service_name__.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:RPC.rpcHead.service_name_)
}
inline void rpcHead::set_service_name_(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  service_name__.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:RPC.rpcHead.service_name_)
}
inline void rpcHead::set_service_name_(const void* value,
    size_t size) {
  
  service_name__.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:RPC.rpcHead.service_name_)
}
inline std::string* rpcHead::_internal_mutable_service_name_() {
  
  return service_name__.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* rpcHead::release_service_name_() {
  // @@protoc_insertion_point(field_release:RPC.rpcHead.service_name_)
  return service_name__.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void rpcHead::set_allocated_service_name_(std::string* service_name_) {
  if (service_name_ != nullptr) {
    
  } else {
    
  }
  service_name__.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), service_name_,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:RPC.rpcHead.service_name_)
}
inline std::string* rpcHead::unsafe_arena_release_service_name_() {
  // @@protoc_insertion_point(field_unsafe_arena_release:RPC.rpcHead.service_name_)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return service_name__.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void rpcHead::unsafe_arena_set_allocated_service_name_(
    std::string* service_name_) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (service_name_ != nullptr) {
    
  } else {
    
  }
  service_name__.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      service_name_, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:RPC.rpcHead.service_name_)
}

// bytes method_name_ = 2;
inline void rpcHead::clear_method_name_() {
  method_name__.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& rpcHead::method_name_() const {
  // @@protoc_insertion_point(field_get:RPC.rpcHead.method_name_)
  return _internal_method_name_();
}
inline void rpcHead::set_method_name_(const std::string& value) {
  _internal_set_method_name_(value);
  // @@protoc_insertion_point(field_set:RPC.rpcHead.method_name_)
}
inline std::string* rpcHead::mutable_method_name_() {
  // @@protoc_insertion_point(field_mutable:RPC.rpcHead.method_name_)
  return _internal_mutable_method_name_();
}
inline const std::string& rpcHead::_internal_method_name_() const {
  return method_name__.Get();
}
inline void rpcHead::_internal_set_method_name_(const std::string& value) {
  
  method_name__.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void rpcHead::set_method_name_(std::string&& value) {
  
  method_name__.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:RPC.rpcHead.method_name_)
}
inline void rpcHead::set_method_name_(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  method_name__.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:RPC.rpcHead.method_name_)
}
inline void rpcHead::set_method_name_(const void* value,
    size_t size) {
  
  method_name__.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:RPC.rpcHead.method_name_)
}
inline std::string* rpcHead::_internal_mutable_method_name_() {
  
  return method_name__.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* rpcHead::release_method_name_() {
  // @@protoc_insertion_point(field_release:RPC.rpcHead.method_name_)
  return method_name__.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void rpcHead::set_allocated_method_name_(std::string* method_name_) {
  if (method_name_ != nullptr) {
    
  } else {
    
  }
  method_name__.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), method_name_,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:RPC.rpcHead.method_name_)
}
inline std::string* rpcHead::unsafe_arena_release_method_name_() {
  // @@protoc_insertion_point(field_unsafe_arena_release:RPC.rpcHead.method_name_)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return method_name__.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void rpcHead::unsafe_arena_set_allocated_method_name_(
    std::string* method_name_) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (method_name_ != nullptr) {
    
  } else {
    
  }
  method_name__.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      method_name_, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:RPC.rpcHead.method_name_)
}

// int32 args_size_ = 3;
inline void rpcHead::clear_args_size_() {
  args_size__ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 rpcHead::_internal_args_size_() const {
  return args_size__;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 rpcHead::args_size_() const {
  // @@protoc_insertion_point(field_get:RPC.rpcHead.args_size_)
  return _internal_args_size_();
}
inline void rpcHead::_internal_set_args_size_(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  args_size__ = value;
}
inline void rpcHead::set_args_size_(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_args_size_(value);
  // @@protoc_insertion_point(field_set:RPC.rpcHead.args_size_)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace RPC

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rpcHead_2eproto
